/* 菜篮 Basket — the knowledge layer.

   FOODS rows are [english names, 中文名, aisle, nutrition groups]. Names are
   comma-separated and the first one is canonical, so an item typed in either
   language finds the same food and lands in the same section. Groups drive the
   weekly balance; seasonings and cooking oil deliberately carry none, otherwise
   every stir-fry would score a serving of fat.

   RECIPES rows are [dish names, ingredients]. Ingredients are written the way
   you would say them out loud — the same parser that reads your typing reads
   them, so "2 番茄" and "2 tomatoes" both resolve to the tomato entry. */

/* ── aisles, in the order you walk the shop ─────────────────── */
const AISLES = [
  { id: 'fruit',   en: 'Fruit',             zh: '水果',      c: '#FF6B6B' },
  { id: 'veg',     en: 'Vegetables',        zh: '蔬菜',      c: '#3FB27F' },
  { id: 'arom',    en: 'Herbs & aromatics', zh: '葱姜蒜',    c: '#8CB800' },
  { id: 'meat',    en: 'Meat & poultry',    zh: '肉类',      c: '#FF7BA0' },
  { id: 'sea',     en: 'Seafood',           zh: '海鲜',      c: '#3FA7DC' },
  { id: 'dairy',   en: 'Eggs & dairy',      zh: '蛋 · 奶',   c: '#F0B429' },
  { id: 'soy',     en: 'Tofu & soy',        zh: '豆制品',    c: '#9B87E0' },
  { id: 'grain',   en: 'Grains & noodles',  zh: '米面',      c: '#F08A3C' },
  { id: 'bake',    en: 'Bakery',            zh: '面包',      c: '#C08552' },
  { id: 'bean',    en: 'Beans & nuts',      zh: '豆 · 坚果', c: '#A0785A' },
  { id: 'pantry',  en: 'Pantry & sauces',   zh: '调料',      c: '#2FB5A6' },
  { id: 'spice',   en: 'Spices & dry',      zh: '香料干货',  c: '#E4633C' },
  { id: 'frozen',  en: 'Frozen',            zh: '冷冻',      c: '#4EC3E8' },
  { id: 'drink',   en: 'Drinks',            zh: '饮品',      c: '#8E7CF0' },
  { id: 'home',    en: 'Household',         zh: '日用',      c: '#8E959B' },
  { id: 'other',   en: 'Other',             zh: '其他',      c: '#A8AEB4' },
];

/* ── where you buy it ───────────────────────────────────────
   Mostly Safeway, T&T for the Asian half of the pantry, Lina's for the
   Italian end. Every item carries its own store and can be moved. */
const STORES = [
  { id: 'safeway', name: 'Safeway', zh: '', c: '#D2372E' },
  { id: 'tnt',     name: 'T&T',     zh: '大统华', c: '#E8830C' },
  { id: 'linas',   name: "Lina's",  zh: '意式', c: '#2F9E44' },
  { id: 'any',     name: 'Anywhere', zh: '哪都行', c: '#8E959B' },
];
const DEFAULT_STORE = 'safeway';

/* foods worth a special trip — everything unlisted is Safeway */
const STORE_OF = {};
for (const id of ('soy sauce,light soy sauce|dark soy sauce|oyster sauce|black vinegar|cooking wine,shaoxing wine|' +
  'sesame oil|doubanjiang,chili bean paste|sweet bean sauce|hoisin sauce|chili oil|fish sauce|fermented black beans|' +
  'fermented tofu|pickled chili|sesame paste,tahini|mirin|sichuan peppercorn|star anise|five spice powder|' +
  'thirteen spice|dried chili|dried shiitake|goji berry|chicken bouillon|rock sugar|cornstarch,corn starch|' +
  'tofu|firm tofu|silken tofu|fried tofu puff|dried tofu|tofu skin|soy milk|edamame|' +
  'rice noodles|glass noodles,vermicelli|ramen|udon|noodles,noodle|dumpling wrappers|wonton wrappers|' +
  'spring roll wrappers|glutinous rice,sticky rice|jasmine rice|frozen dumplings|steamed bun,mantou|' +
  'napa cabbage|bok choy,pak choi|baby bok choy|choy sum|chinese broccoli,gai lan|chinese chives|garlic sprout,garlic scape|' +
  'lotus root|bamboo shoot|water chestnut|taro|chinese yam|daikon,white radish|bitter melon|winter melon|' +
  'luffa,silk squash|wood ear|enoki|king oyster mushroom|oyster mushroom|shiitake|bean sprout|pea shoot|' +
  'amaranth greens|celtuce|seaweed,nori|kelp|pickled mustard greens|preserved vegetable|' +
  'century egg|salted duck egg|quail egg|dried shrimp|fish ball|squid|eel|pork belly|pork ribs|beef brisket|' +
  'chicken feet|tripe|lychee|longan|dragon fruit|persimmon|milk tea').split('|')) {
  STORE_OF[id.split(',')[0]] = 'tnt';
}
for (const id of ('parmesan|mozzarella|prosciutto|salami|olive|olive oil|basil|oregano|pasta,spaghetti|penne|' +
  'lasagna sheets|pine nut|canned tomatoes|tomato paste|breadcrumbs|focaccia|cream cheese').split('|')) {
  STORE_OF[id.split(',')[0]] = 'linas';
}

/* ── the six things a balanced day needs ────────────────────── */
const GROUPS = [
  { id: 'veg',     en: 'Vegetables',  zh: '蔬菜',     short: '蔬菜', color: '#3fb27f', perDay: 3 },
  { id: 'fruit',   en: 'Fruit',       zh: '水果',     short: '水果', color: '#e0705a', perDay: 2 },
  { id: 'grain',   en: 'Grains',      zh: '主食',     short: '主食', color: '#d9a441', perDay: 3 },
  { id: 'protein', en: 'Protein',     zh: '蛋白质',   short: '蛋白', color: '#4f8ff7', perDay: 3 },
  { id: 'dairy',   en: 'Dairy',       zh: '奶制品',   short: '奶类', color: '#8f7ee0', perDay: 1 },
  { id: 'fat',     en: 'Nuts & fats', zh: '坚果油脂', short: '油脂', color: '#a08767', perDay: 1 },
];

/* the three a single meal is judged on */
const CORE_GROUPS = ['veg', 'protein', 'grain'];

const MEALS = [
  { id: 'breakfast', en: 'Breakfast', zh: '早餐' },
  { id: 'lunch',     en: 'Lunch',     zh: '午餐' },
  { id: 'dinner',    en: 'Dinner',    zh: '晚餐' },
  { id: 'snack',     en: 'Snacks',    zh: '加餐', optional: true },
];

/* ── the pantry itself ──────────────────────────────────────── */
const FOODS = [
  /* fruit */
  ['apple', '苹果', 'fruit', 'fruit'],
  ['banana', '香蕉', 'fruit', 'fruit'],
  ['orange', '橙子,橙,柳丁', 'fruit', 'fruit'],
  ['mandarin,tangerine', '橘子,桔子,砂糖橘', 'fruit', 'fruit'],
  ['grapefruit,pomelo', '西柚,葡萄柚,柚子', 'fruit', 'fruit'],
  ['lemon', '柠檬', 'fruit', 'fruit'],
  ['lime', '青柠', 'fruit', 'fruit'],
  ['grape', '葡萄,提子', 'fruit', 'fruit'],
  ['strawberry', '草莓', 'fruit', 'fruit'],
  ['blueberry', '蓝莓', 'fruit', 'fruit'],
  ['raspberry', '树莓,覆盆子', 'fruit', 'fruit'],
  ['blackberry', '黑莓', 'fruit', 'fruit'],
  ['watermelon', '西瓜', 'fruit', 'fruit'],
  ['melon,cantaloupe', '哈密瓜,甜瓜', 'fruit', 'fruit'],
  ['pineapple', '菠萝,凤梨', 'fruit', 'fruit'],
  ['mango', '芒果', 'fruit', 'fruit'],
  ['peach', '桃子,水蜜桃,黄桃', 'fruit', 'fruit'],
  ['pear', '梨,梨子,雪梨', 'fruit', 'fruit'],
  ['plum', '李子,布林', 'fruit', 'fruit'],
  ['cherry', '樱桃,车厘子', 'fruit', 'fruit'],
  ['kiwi,kiwifruit', '猕猴桃,奇异果', 'fruit', 'fruit'],
  ['pomegranate', '石榴', 'fruit', 'fruit'],
  ['persimmon', '柿子', 'fruit', 'fruit'],
  ['lychee', '荔枝', 'fruit', 'fruit'],
  ['longan', '龙眼,桂圆', 'fruit', 'fruit'],
  ['dragon fruit', '火龙果', 'fruit', 'fruit'],
  ['papaya', '木瓜', 'fruit', 'fruit'],
  ['guava', '番石榴,芭乐', 'fruit', 'fruit'],
  ['apricot', '杏,杏子', 'fruit', 'fruit'],
  ['fig', '无花果', 'fruit', 'fruit'],
  ['coconut', '椰子', 'fruit', 'fat'],
  ['avocado', '牛油果,鳄梨', 'fruit', 'fat'],   /* bought as fruit, eaten as a fat */
  ['red date,jujube', '红枣,大枣', 'fruit', 'fruit'],
  ['raisin', '葡萄干', 'fruit', 'fruit'],
  ['dried cranberry', '蔓越莓干', 'fruit', 'fruit'],

  /* vegetables */
  ['tomato', '番茄,西红柿', 'veg', 'veg'],
  ['cherry tomato', '圣女果,小番茄', 'veg', 'veg'],
  ['cucumber', '黄瓜,青瓜', 'veg', 'veg'],
  ['carrot', '胡萝卜', 'veg', 'veg'],
  ['potato', '土豆,马铃薯', 'veg', 'veg grain'],
  ['sweet potato', '红薯,地瓜,番薯', 'veg', 'veg grain'],
  ['onion', '洋葱', 'veg', 'veg'],
  ['bell pepper,capsicum', '彩椒,甜椒,柿子椒', 'veg', 'veg'],
  ['green pepper', '青椒', 'veg', 'veg'],
  ['chili pepper,chilli,chili', '辣椒,小米椒,尖椒', 'veg', 'veg'],
  ['broccoli', '西兰花,西蓝花', 'veg', 'veg'],
  ['cauliflower', '花菜,菜花,有机花菜', 'veg', 'veg'],
  ['cabbage', '卷心菜,包菜,圆白菜', 'veg', 'veg'],
  ['napa cabbage', '大白菜', 'veg', 'veg'],
  ['bok choy,pak choi', '小白菜,青菜,上海青', 'veg', 'veg'],
  ['baby bok choy', '娃娃菜', 'veg', 'veg'],
  ['choy sum', '菜心', 'veg', 'veg'],
  ['chinese broccoli,gai lan', '芥兰,芥蓝', 'veg', 'veg'],
  ['spinach', '菠菜', 'veg', 'veg'],
  ['lettuce', '生菜', 'veg', 'veg'],
  ['romaine', '罗马生菜', 'veg', 'veg'],
  ['kale', '羽衣甘蓝', 'veg', 'veg'],
  ['arugula,rocket', '芝麻菜', 'veg', 'veg'],
  ['celery', '芹菜,西芹', 'veg', 'veg'],
  ['asparagus', '芦笋', 'veg', 'veg'],
  ['zucchini,courgette', '西葫芦', 'veg', 'veg'],
  ['eggplant,aubergine', '茄子', 'veg', 'veg'],
  ['pumpkin', '南瓜', 'veg', 'veg'],
  ['winter melon', '冬瓜', 'veg', 'veg'],
  ['bitter melon', '苦瓜', 'veg', 'veg'],
  ['luffa,silk squash', '丝瓜', 'veg', 'veg'],
  ['chayote', '佛手瓜', 'veg', 'veg'],
  ['green bean,string bean', '四季豆,豆角,长豆角', 'veg', 'veg'],
  ['snow pea', '荷兰豆', 'veg', 'veg'],
  ['sugar snap pea', '甜豆', 'veg', 'veg'],
  ['pea,green pea', '豌豆,青豆', 'veg', 'veg protein'],
  ['corn,sweetcorn', '玉米,甜玉米', 'veg', 'veg grain'],
  ['mushroom,button mushroom', '蘑菇,口蘑', 'veg', 'veg'],
  ['shiitake', '香菇,冬菇', 'veg', 'veg'],
  ['enoki', '金针菇', 'veg', 'veg'],
  ['king oyster mushroom', '杏鲍菇', 'veg', 'veg'],
  ['oyster mushroom', '平菇', 'veg', 'veg'],
  ['wood ear', '木耳,黑木耳', 'veg', 'veg'],
  ['bean sprout', '豆芽,绿豆芽,黄豆芽', 'veg', 'veg'],
  ['pea shoot', '豆苗', 'veg', 'veg'],
  ['lotus root', '莲藕,藕', 'veg', 'veg'],
  ['bamboo shoot', '竹笋,笋', 'veg', 'veg'],
  ['water chestnut', '荸荠,马蹄', 'veg', 'veg'],
  ['taro', '芋头', 'veg', 'veg grain'],
  ['chinese yam', '山药', 'veg', 'veg'],
  ['daikon,white radish', '白萝卜,萝卜', 'veg', 'veg'],
  ['beetroot,beet', '甜菜根', 'veg', 'veg'],
  ['okra', '秋葵', 'veg', 'veg'],
  ['brussels sprout', '抱子甘蓝', 'veg', 'veg'],
  ['celtuce', '莴笋', 'veg', 'veg'],
  ['amaranth greens', '苋菜', 'veg', 'veg'],
  ['garlic sprout,garlic scape', '蒜苗,蒜薹', 'veg', 'veg'],
  ['chinese chives', '韭菜', 'veg', 'veg'],
  ['watercress', '西洋菜', 'veg', 'veg'],
  ['seaweed,nori', '紫菜,海苔', 'veg', 'veg'],
  ['kelp', '海带', 'veg', 'veg'],
  ['pickled mustard greens', '酸菜', 'veg', 'veg'],
  ['pickle,dill pickle', '酸黄瓜', 'veg', 'veg'],
  ['preserved vegetable', '榨菜,梅干菜', 'veg', 'veg'],
  ['olive', '橄榄', 'veg', 'fat'],

  /* aromatics + herbs */
  ['garlic', '大蒜,蒜,蒜头,蒜瓣', 'arom', ''],
  ['ginger', '生姜,姜', 'arom', ''],
  ['scallion,spring onion,green onion', '葱,小葱,香葱,大葱', 'arom', ''],
  ['shallot', '红葱头', 'arom', ''],
  ['leek', '韭葱', 'arom', ''],
  ['cilantro,coriander', '香菜,芫荽', 'arom', ''],
  ['parsley', '欧芹', 'arom', ''],
  ['basil', '罗勒,九层塔', 'arom', ''],
  ['mint', '薄荷', 'arom', ''],
  ['rosemary', '迷迭香', 'arom', ''],
  ['thyme', '百里香', 'arom', ''],
  ['dill', '莳萝', 'arom', ''],
  ['lemongrass', '香茅', 'arom', ''],

  /* meat */
  ['chicken', '鸡肉,鸡', 'meat', 'protein'],
  ['chicken breast', '鸡胸肉,鸡胸', 'meat', 'protein'],
  ['chicken thigh', '鸡腿肉,鸡腿,琵琶腿', 'meat', 'protein'],
  ['chicken wing', '鸡翅,鸡翅膀', 'meat', 'protein'],
  ['whole chicken', '整鸡,三黄鸡', 'meat', 'protein'],
  ['chicken feet', '鸡爪,凤爪', 'meat', 'protein'],
  ['pork', '猪肉', 'meat', 'protein'],
  ['pork belly', '五花肉', 'meat', 'protein'],
  ['pork loin,pork tenderloin', '里脊,猪里脊,通脊', 'meat', 'protein'],
  ['ground pork,minced pork', '猪肉末,肉末,肉馅,猪绞肉', 'meat', 'protein'],
  ['pork ribs', '排骨,肋排', 'meat', 'protein'],
  ['pork shoulder', '梅花肉', 'meat', 'protein'],
  ['beef', '牛肉', 'meat', 'protein'],
  ['ground beef,minced beef', '牛肉末,牛肉馅,牛绞肉', 'meat', 'protein'],
  ['steak', '牛排', 'meat', 'protein'],
  ['beef brisket', '牛腩', 'meat', 'protein'],
  ['beef shank', '牛腱,牛腱子', 'meat', 'protein'],
  ['lamb,mutton', '羊肉', 'meat', 'protein'],
  ['lamb chop', '羊排', 'meat', 'protein'],
  ['duck', '鸭肉,鸭', 'meat', 'protein'],
  ['bacon', '培根', 'meat', 'protein'],
  ['sausage', '香肠,腊肠,烤肠', 'meat', 'protein'],
  ['ham', '火腿', 'meat', 'protein'],
  ['deli turkey,turkey slices', '火鸡片', 'meat', 'protein'],
  ['prosciutto', '意式火腿', 'meat', 'protein'],
  ['salami', '萨拉米', 'meat', 'protein'],
  ['pork liver', '猪肝', 'meat', 'protein'],
  ['tripe', '牛肚,毛肚', 'meat', 'protein'],
  ['meatball', '肉丸,丸子', 'meat', 'protein'],

  /* seafood */
  ['fish', '鱼', 'sea', 'protein'],
  ['salmon', '三文鱼,鲑鱼', 'sea', 'protein fat'],
  ['tuna,canned tuna', '金枪鱼,吞拿鱼,金枪鱼罐头', 'sea', 'protein'],
  ['cod', '鳕鱼', 'sea', 'protein'],
  ['sea bass', '鲈鱼', 'sea', 'protein'],
  ['tilapia', '罗非鱼', 'sea', 'protein'],
  ['grass carp', '草鱼', 'sea', 'protein'],
  ['crucian carp', '鲫鱼', 'sea', 'protein'],
  ['shrimp,prawn', '虾,基围虾,大虾,虾仁', 'sea', 'protein'],
  ['crab', '螃蟹,蟹', 'sea', 'protein'],
  ['squid', '鱿鱼', 'sea', 'protein'],
  ['clam', '蛤蜊,花甲', 'sea', 'protein'],
  ['mussel', '青口,贻贝', 'sea', 'protein'],
  ['scallop', '扇贝,带子', 'sea', 'protein'],
  ['oyster', '生蚝,牡蛎', 'sea', 'protein'],
  ['dried shrimp', '虾米,虾皮', 'sea', 'protein'],
  ['fish ball', '鱼丸', 'sea', 'protein'],
  ['eel', '鳗鱼', 'sea', 'protein'],

  /* eggs + dairy */
  ['egg', '鸡蛋,蛋', 'dairy', 'protein'],
  ['quail egg', '鹌鹑蛋', 'dairy', 'protein'],
  ['century egg', '皮蛋', 'dairy', 'protein'],
  ['salted duck egg', '咸鸭蛋', 'dairy', 'protein'],
  ['milk', '牛奶,鲜奶', 'dairy', 'dairy'],
  ['yogurt', '酸奶', 'dairy', 'dairy'],
  ['greek yogurt', '希腊酸奶', 'dairy', 'dairy protein'],
  ['cheese', '奶酪,芝士', 'dairy', 'dairy'],
  ['cheddar', '切达奶酪', 'dairy', 'dairy'],
  ['mozzarella', '马苏里拉', 'dairy', 'dairy'],
  ['parmesan', '帕玛森,芝士粉', 'dairy', 'dairy'],
  ['cream cheese', '奶油奶酪', 'dairy', 'dairy'],
  ['cream,heavy cream', '淡奶油', 'dairy', 'dairy fat'],
  ['sour cream', '酸奶油', 'dairy', 'dairy'],
  ['butter', '黄油', 'dairy', 'fat'],
  ['condensed milk', '炼乳', 'dairy', 'dairy'],
  ['oat milk', '燕麦奶', 'dairy', 'grain'],
  ['almond milk', '杏仁奶', 'dairy', 'fat'],

  /* soy */
  ['tofu', '豆腐', 'soy', 'protein'],
  ['firm tofu', '老豆腐,北豆腐', 'soy', 'protein'],
  ['silken tofu', '嫩豆腐,内酯豆腐', 'soy', 'protein'],
  ['fried tofu puff', '油豆腐,豆泡', 'soy', 'protein'],
  ['dried tofu', '豆干,香干', 'soy', 'protein'],
  ['tofu skin', '腐竹,豆皮', 'soy', 'protein'],
  ['tempeh', '天贝', 'soy', 'protein'],
  ['edamame', '毛豆', 'soy', 'protein veg'],
  ['soy milk', '豆浆', 'soy', 'protein'],

  /* grains + noodles */
  ['rice', '大米,白米,米饭,米', 'grain', 'grain'],
  ['jasmine rice', '香米', 'grain', 'grain'],
  ['brown rice', '糙米', 'grain', 'grain'],
  ['glutinous rice,sticky rice', '糯米', 'grain', 'grain'],
  ['quinoa', '藜麦', 'grain', 'grain protein'],
  ['oats,oatmeal,rolled oats', '燕麦,燕麦片', 'grain', 'grain'],
  ['millet', '小米', 'grain', 'grain'],
  ['barley', '大麦,薏米', 'grain', 'grain'],
  ['flour', '面粉', 'grain', 'grain'],
  ['noodles,noodle', '面条,挂面', 'grain', 'grain'],
  ['ramen', '拉面', 'grain', 'grain'],
  ['udon', '乌冬面', 'grain', 'grain'],
  ['rice noodles', '米粉,河粉,粿条', 'grain', 'grain'],
  ['glass noodles,vermicelli', '粉丝,细粉,红薯粉', 'grain', 'grain'],
  ['pasta,spaghetti', '意面,意大利面,意粉', 'grain', 'grain'],
  ['penne', '通心粉', 'grain', 'grain'],
  ['lasagna sheets', '千层面皮', 'grain', 'grain'],
  ['couscous', '古斯米', 'grain', 'grain'],
  ['dumpling wrappers', '饺子皮', 'grain', 'grain'],
  ['wonton wrappers', '馄饨皮', 'grain', 'grain'],
  ['spring roll wrappers', '春卷皮', 'grain', 'grain'],
  ['tortilla', '墨西哥饼皮,玉米饼', 'grain', 'grain'],
  ['cereal', '麦片', 'grain', 'grain'],
  ['breadcrumbs', '面包糠', 'grain', 'grain'],

  /* bakery */
  ['bread', '面包', 'bake', 'grain'],
  ['whole wheat bread', '全麦面包', 'bake', 'grain'],
  ['toast,sliced bread', '吐司', 'bake', 'grain'],
  ['steamed bun,mantou', '馒头', 'bake', 'grain'],
  ['bagel', '贝果', 'bake', 'grain'],
  ['croissant', '可颂,牛角包', 'bake', 'grain fat'],
  ['pita', '皮塔饼', 'bake', 'grain'],
  ['focaccia', '佛卡夏', 'bake', 'grain'],
  ['cake', '蛋糕', 'bake', 'grain'],
  ['scallion pancake', '葱油饼', 'bake', 'grain'],

  /* beans + nuts */
  ['black bean', '黑豆', 'bean', 'protein'],
  ['kidney bean', '芸豆,红腰豆', 'bean', 'protein'],
  ['chickpea', '鹰嘴豆', 'bean', 'protein'],
  ['lentil', '扁豆,小扁豆', 'bean', 'protein'],
  ['mung bean', '绿豆', 'bean', 'protein'],
  ['red bean,adzuki', '红豆', 'bean', 'protein'],
  ['soybean', '黄豆', 'bean', 'protein'],
  ['peanut', '花生', 'bean', 'fat protein'],
  ['almond', '杏仁', 'bean', 'fat'],
  ['walnut', '核桃', 'bean', 'fat'],
  ['cashew', '腰果', 'bean', 'fat'],
  ['pistachio', '开心果', 'bean', 'fat'],
  ['pine nut', '松子', 'bean', 'fat'],
  ['sesame seed', '芝麻', 'bean', 'fat'],
  ['sunflower seed', '瓜子,葵花籽', 'bean', 'fat'],
  ['pumpkin seed', '南瓜子', 'bean', 'fat'],
  ['chia seed', '奇亚籽', 'bean', 'fat'],
  ['flaxseed', '亚麻籽', 'bean', 'fat'],
  ['peanut butter', '花生酱', 'bean', 'fat protein'],

  /* pantry */
  ['soy sauce,light soy sauce', '生抽,酱油', 'pantry', ''],
  ['dark soy sauce', '老抽', 'pantry', ''],
  ['oyster sauce', '蚝油', 'pantry', ''],
  ['vinegar,rice vinegar', '米醋,醋', 'pantry', ''],
  ['black vinegar', '陈醋,香醋', 'pantry', ''],
  ['cooking wine,shaoxing wine', '料酒,黄酒,绍兴酒', 'pantry', ''],
  ['sesame oil', '香油,麻油', 'pantry', ''],
  ['cooking oil,vegetable oil,oil', '食用油,菜籽油,油', 'pantry', ''],
  ['olive oil', '橄榄油', 'pantry', ''],
  ['salt', '盐,食盐', 'pantry', ''],
  ['sugar', '白糖,砂糖,糖', 'pantry', ''],
  ['rock sugar', '冰糖', 'pantry', ''],
  ['brown sugar', '红糖', 'pantry', ''],
  ['honey', '蜂蜜', 'pantry', ''],
  ['chicken bouillon', '鸡精,味精', 'pantry', ''],
  ['doubanjiang,chili bean paste', '豆瓣酱', 'pantry', ''],
  ['sweet bean sauce', '甜面酱', 'pantry', ''],
  ['hoisin sauce', '海鲜酱', 'pantry', ''],
  ['chili oil', '辣椒油,红油', 'pantry', ''],
  ['chili sauce,sriracha', '辣椒酱,蒜蓉辣酱', 'pantry', ''],
  ['ketchup', '番茄酱', 'pantry', ''],
  ['mayonnaise', '蛋黄酱,沙拉酱', 'pantry', ''],
  ['mustard', '芥末', 'pantry', ''],
  ['fish sauce', '鱼露', 'pantry', ''],
  ['mirin', '味淋', 'pantry', ''],
  ['furikake', '香松', 'pantry', ''],
  ['curry paste,curry sauce', '咖喱块,咖喱酱', 'pantry', ''],
  ['tomato paste', '番茄膏', 'pantry', ''],
  ['canned tomatoes', '番茄罐头', 'pantry', 'veg'],
  ['coconut milk', '椰奶,椰浆', 'pantry', 'fat'],
  ['stock,broth', '高汤,鸡汤', 'pantry', ''],
  ['sesame paste,tahini', '芝麻酱', 'pantry', 'fat'],
  ['fermented black beans', '豆豉', 'pantry', ''],
  ['fermented tofu', '腐乳', 'pantry', ''],
  ['pickled chili', '泡椒', 'pantry', ''],
  ['cornstarch,corn starch', '淀粉,生粉,玉米淀粉', 'pantry', ''],
  ['potato starch', '土豆淀粉', 'pantry', ''],
  ['baking powder', '泡打粉', 'pantry', ''],
  ['yeast', '酵母', 'pantry', ''],
  ['vanilla extract', '香草精', 'pantry', ''],
  ['jam', '果酱', 'pantry', ''],
  ['maple syrup', '枫糖浆', 'pantry', ''],

  /* spices */
  ['black pepper,pepper', '黑胡椒,胡椒', 'spice', ''],
  ['white pepper', '白胡椒', 'spice', ''],
  ['sichuan peppercorn', '花椒', 'spice', ''],
  ['star anise', '八角,大料', 'spice', ''],
  ['cinnamon', '桂皮,肉桂', 'spice', ''],
  ['clove', '丁香', 'spice', ''],
  ['fennel seed', '小茴香', 'spice', ''],
  ['cumin', '孜然', 'spice', ''],
  ['chili flakes,chili powder', '辣椒面,辣椒粉', 'spice', ''],
  ['five spice powder', '五香粉', 'spice', ''],
  ['thirteen spice', '十三香', 'spice', ''],
  ['bay leaf', '香叶,月桂叶', 'spice', ''],
  ['dried chili', '干辣椒', 'spice', ''],
  ['turmeric', '姜黄', 'spice', ''],
  ['paprika', '红椒粉', 'spice', ''],
  ['oregano', '牛至', 'spice', ''],
  ['curry powder', '咖喱粉', 'spice', ''],
  ['dried shiitake', '干香菇', 'spice', 'veg'],
  ['goji berry', '枸杞', 'spice', 'fruit'],

  /* frozen */
  ['frozen dumplings', '速冻饺子', 'frozen', 'grain protein'],
  ['frozen peas', '冷冻豌豆', 'frozen', 'veg'],
  ['frozen berries', '冷冻莓果', 'frozen', 'fruit'],
  ['ice cream', '冰淇淋,雪糕', 'frozen', 'dairy'],

  /* drinks */
  ['water,bottled water', '水,矿泉水', 'drink', ''],
  ['sparkling water', '气泡水', 'drink', ''],
  ['tea', '茶,茶叶', 'drink', ''],
  ['green tea', '绿茶', 'drink', ''],
  ['coffee', '咖啡', 'drink', ''],
  ['orange juice', '橙汁', 'drink', 'fruit'],
  ['juice', '果汁', 'drink', 'fruit'],
  ['beer', '啤酒', 'drink', ''],
  ['wine', '红酒,葡萄酒', 'drink', ''],
  ['cola,soda', '可乐,汽水', 'drink', ''],
  ['milk tea', '奶茶', 'drink', 'dairy'],

  /* household */
  ['paper towels', '厨房纸', 'home', ''],
  ['toilet paper', '卫生纸,厕纸', 'home', ''],
  ['dish soap', '洗洁精', 'home', ''],
  ['laundry detergent', '洗衣液', 'home', ''],
  ['trash bags', '垃圾袋', 'home', ''],
  ['aluminium foil,foil', '锡纸,铝箔纸', 'home', ''],
  ['plastic wrap,cling film', '保鲜膜', 'home', ''],
  ['sponge', '海绵,洗碗布', 'home', ''],
  ['ziplock bags', '密封袋', 'home', ''],
];

/* ── the recipe book ────────────────────────────────────────
   Write a dish in either language and these are what land in the list. */
const RECIPES = [
  /* 家常菜 */
  ['番茄炒蛋,西红柿炒鸡蛋,tomato and egg,tomato egg stir fry',
   '3 番茄; 4 鸡蛋; 葱; 盐; 白糖; 食用油'],
  ['宫保鸡丁,kung pao chicken,gong bao chicken',
   '400克 鸡胸肉; 100克 花生; 干辣椒; 花椒; 葱; 姜; 大蒜; 生抽; 陈醋; 白糖; 淀粉'],
  ['麻婆豆腐,mapo tofu',
   '1盒 嫩豆腐; 150克 猪肉末; 豆瓣酱; 花椒; 葱; 大蒜; 淀粉; 生抽'],
  ['红烧肉,braised pork belly',
   '700克 五花肉; 冰糖; 生抽; 老抽; 料酒; 姜; 葱; 八角; 桂皮'],
  ['红烧排骨,braised pork ribs',
   '700克 排骨; 冰糖; 生抽; 老抽; 料酒; 姜; 葱; 八角'],
  ['糖醋里脊,sweet and sour pork',
   '500克 里脊; 番茄酱; 白糖; 米醋; 淀粉; 鸡蛋; 食用油'],
  ['鱼香肉丝,yuxiang pork,fish fragrant pork',
   '300克 里脊; 木耳; 胡萝卜; 竹笋; 豆瓣酱; 泡椒; 大蒜; 姜; 葱; 陈醋; 白糖; 淀粉'],
  ['回锅肉,twice cooked pork',
   '400克 五花肉; 卷心菜; 青椒; 豆瓣酱; 甜面酱; 葱; 姜; 大蒜'],
  ['青椒肉丝,pork with green pepper',
   '300克 里脊; 3 青椒; 生抽; 淀粉; 大蒜; 姜'],
  ['蒜蓉西兰花,garlic broccoli',
   '1 西兰花; 大蒜; 盐; 蚝油; 食用油'],
  ['地三鲜,di san xian',
   '2 茄子; 3 土豆; 2 青椒; 大蒜; 生抽; 白糖; 淀粉'],
  ['干煸四季豆,dry fried green beans',
   '500克 四季豆; 100克 猪肉末; 干辣椒; 花椒; 大蒜; 生抽'],
  ['酸辣土豆丝,hot and sour potato',
   '3 土豆; 干辣椒; 花椒; 陈醋; 大蒜; 葱'],
  ['清蒸鱼,steamed fish',
   '1条 鲈鱼; 姜; 葱; 生抽; 料酒; 香菜'],
  ['可乐鸡翅,cola chicken wings',
   '12 鸡翅; 可乐; 生抽; 姜; 葱; 料酒'],
  ['三杯鸡,three cup chicken',
   '600克 鸡腿肉; 香油; 生抽; 料酒; 姜; 大蒜; 罗勒; 冰糖'],
  ['咖喱鸡,chicken curry',
   '500克 鸡腿肉; 2 土豆; 2 胡萝卜; 1 洋葱; 咖喱块; 椰奶'],
  ['土豆炖牛肉,beef and potato stew',
   '600克 牛腩; 3 土豆; 2 胡萝卜; 1 洋葱; 生抽; 老抽; 八角; 桂皮; 姜'],
  ['番茄牛腩,tomato beef brisket',
   '700克 牛腩; 4 番茄; 1 洋葱; 番茄膏; 姜; 八角'],
  ['酸菜鱼,sauerkraut fish',
   '1条 草鱼; 酸菜; 泡椒; 花椒; 干辣椒; 姜; 大蒜; 淀粉; 鸡蛋'],
  ['水煮肉片,boiled pork in chili oil',
   '400克 里脊; 豆芽; 生菜; 豆瓣酱; 花椒; 干辣椒; 淀粉; 大蒜'],
  ['蛋炒饭,egg fried rice,fried rice,炒饭',
   '3碗 米饭; 3 鸡蛋; 葱; 豌豆; 胡萝卜; 生抽; 食用油'],
  ['扬州炒饭,yangzhou fried rice',
   '3碗 米饭; 3 鸡蛋; 虾仁; 火腿; 豌豆; 胡萝卜; 葱'],
  ['炒面,fried noodles,chow mein',
   '400克 面条; 200克 猪肉; 卷心菜; 胡萝卜; 豆芽; 葱; 生抽; 蚝油'],
  ['牛肉面,beef noodle soup',
   '600克 牛腩; 400克 面条; 小白菜; 葱; 姜; 八角; 桂皮; 豆瓣酱; 生抽'],
  ['饺子,dumplings,水饺',
   '饺子皮; 400克 猪肉末; 大白菜; 韭菜; 葱; 姜; 香油; 生抽'],
  ['馄饨,wonton',
   '馄饨皮; 300克 猪肉末; 虾仁; 葱; 姜; 香油; 紫菜'],
  ['皮蛋瘦肉粥,century egg congee,congee,粥',
   '1杯 大米; 2 皮蛋; 200克 里脊; 姜; 葱; 盐'],
  ['冬瓜排骨汤,winter melon rib soup',
   '500克 排骨; 1块 冬瓜; 姜; 枸杞; 盐'],
  ['西红柿鸡蛋汤,tomato egg soup',
   '2 番茄; 2 鸡蛋; 葱; 香油; 盐; 淀粉'],
  ['紫菜蛋花汤,seaweed egg drop soup',
   '紫菜; 2 鸡蛋; 虾皮; 葱; 香油'],
  ['蒸蛋羹,steamed egg custard',
   '3 鸡蛋; 生抽; 香油; 葱'],
  ['京酱肉丝,shredded pork in bean sauce',
   '400克 里脊; 甜面酱; 葱; 豆皮; 淀粉; 料酒'],
  ['蚝油生菜,lettuce in oyster sauce',
   '2 生菜; 蚝油; 大蒜; 食用油'],
  ['上汤娃娃菜,baby cabbage in broth',
   '4 娃娃菜; 皮蛋; 高汤; 枸杞; 大蒜'],
  ['孜然羊肉,cumin lamb',
   '500克 羊肉; 孜然; 辣椒面; 洋葱; 香菜; 大蒜'],
  ['凉拌黄瓜,smashed cucumber salad',
   '2 黄瓜; 大蒜; 陈醋; 香油; 辣椒油; 生抽'],
  ['麻辣香锅,mala xiang guo',
   '莲藕; 土豆; 西兰花; 金针菇; 午餐肉; 虾; 豆瓣酱; 花椒; 干辣椒'],
  ['火锅,hot pot',
   '牛肉; 羊肉; 虾; 鱼丸; 娃娃菜; 金针菇; 豆腐; 粉丝; 香菜; 芝麻酱'],
  ['葱油拌面,scallion oil noodles',
   '400克 面条; 葱; 生抽; 老抽; 白糖; 食用油'],
  ['白灼虾,boiled shrimp',
   '500克 虾; 姜; 葱; 生抽'],
  ['蒜蓉粉丝蒸虾,steamed shrimp with garlic vermicelli',
   '500克 虾; 粉丝; 大蒜; 生抽; 葱'],

  /* the regulars */
  ['sesame noodles,芝麻拌面,麻酱面,芝麻面,nouilles au sésame',
   '400g noodles; 芝麻酱; 生抽; 陈醋; 辣椒油; 香油; 大蒜; 葱; 1 黄瓜; 花生; 白糖'],
  ['tuna rice bowl,金枪鱼饭,吞拿鱼饭,bol de riz au thon',
   '2 canned tuna; 2杯 rice; 1 黄瓜; 1 牛油果; 蛋黄酱; 辣椒酱; 紫菜; 芝麻; 葱; 生抽'],
  ['salmon soy bowl,三文鱼饭,酱油三文鱼,bol de saumon au soja',
   '2 salmon; 2杯 rice; 生抽; 味淋; 香油; 1 牛油果; 1 黄瓜; 毛豆; 紫菜; 葱; 芝麻'],
  ['sandwich,三明治,le sandwich',
   'bread; deli turkey; cheese; lettuce; 1 tomato; 1 牛油果; 蛋黄酱; mustard; pickle'],
  ['marinated eggs,卤蛋,溏心蛋,酱油蛋,œufs marinés',
   '6 鸡蛋; 生抽; 味淋; 白糖; 大蒜; 葱; 干辣椒'],

  /* western + everyday */
  ['spaghetti bolognese,bolognese,肉酱意面',
   '400g pasta; 500g ground beef; 1 onion; 2 carrot; celery; canned tomatoes; tomato paste; garlic; olive oil; parmesan'],
  ['carbonara,卡邦尼,培根蛋面',
   '400g spaghetti; 200g bacon; 3 egg; parmesan; black pepper'],
  ['pesto pasta,青酱意面',
   '400g pasta; basil; pine nut; parmesan; olive oil; garlic'],
  ['mac and cheese,芝士通心粉',
   '400g penne; cheddar; milk; butter; flour; breadcrumbs'],
  ['lasagna,千层面',
   'lasagna sheets; 500g ground beef; canned tomatoes; mozzarella; parmesan; milk; butter; flour; onion; garlic'],
  ['caesar salad,凯撒沙拉',
   'romaine; parmesan; bread; chicken breast; mayonnaise; lemon; garlic'],
  ['greek salad,希腊沙拉',
   'cucumber; tomato; red onion; olive; cheese; olive oil; oregano'],
  ['roast chicken,烤鸡',
   '1 whole chicken; potato; carrot; onion; rosemary; thyme; butter; lemon'],
  ['beef stew,炖牛肉',
   '800g beef brisket; potato; carrot; onion; celery; tomato paste; stock; bay leaf'],
  ['chili,chili con carne,辣肉酱',
   '500g ground beef; kidney bean; canned tomatoes; onion; bell pepper; garlic; cumin; paprika'],
  ['tacos,墨西哥卷',
   'tortilla; 500g ground beef; lettuce; tomato; cheddar; sour cream; onion; lime; cumin'],
  ['burrito bowl',
   'rice; black bean; chicken breast; corn; avocado; lettuce; cheddar; lime; sour cream'],
  ['burger,汉堡',
   'bread; 500g ground beef; cheddar; lettuce; tomato; onion; ketchup; mustard'],
  ['pizza,margherita pizza,披萨',
   'flour; yeast; canned tomatoes; mozzarella; basil; olive oil'],
  ['stir fry,蔬菜炒',
   'broccoli; carrot; bell pepper; snow pea; garlic; ginger; soy sauce; sesame oil; rice'],
  ['omelette,煎蛋卷',
   '3 egg; cheese; butter; mushroom; spinach; milk'],
  ['pancakes,松饼',
   'flour; 2 egg; milk; butter; baking powder; maple syrup; banana'],
  ['oatmeal,porridge,燕麦粥',
   'oats; milk; banana; blueberry; walnut; honey'],
  ['avocado toast,牛油果吐司',
   'toast; 2 avocado; 2 egg; lemon; chili flakes'],
  ['grilled cheese,芝士三明治',
   'bread; cheddar; butter; tomato'],
  ['tomato soup,番茄汤',
   'canned tomatoes; onion; garlic; cream; basil; stock; bread'],
  ['chicken noodle soup,鸡汤面',
   'chicken thigh; noodles; carrot; celery; onion; parsley; stock'],
  ['shepherds pie,牧羊人派',
   '500g lamb; potato; carrot; frozen peas; onion; butter; milk; tomato paste'],
  ['salmon and vegetables,烤三文鱼',
   '2 salmon; asparagus; potato; lemon; olive oil; garlic; dill'],
  ['poke bowl',
   'rice; tuna; avocado; cucumber; edamame; seaweed; soy sauce; sesame seed'],
  ['sushi,寿司',
   'sushi rice; salmon; cucumber; avocado; seaweed; rice vinegar; soy sauce'],
  ['ramen,日式拉面',
   'ramen; pork belly; 2 egg; bok choy; scallion; corn; seaweed; stock; soy sauce'],
  ['pad thai,泰式炒河粉',
   'rice noodles; shrimp; 2 egg; bean sprout; peanut; lime; fish sauce; sugar; garlic'],
  ['green curry,泰式绿咖喱',
   'chicken thigh; coconut milk; curry paste; eggplant; bell pepper; basil; fish sauce; rice'],
  ['shakshuka',
   'canned tomatoes; 4 egg; onion; bell pepper; garlic; cumin; paprika; bread'],
  ['hummus,鹰嘴豆泥',
   'chickpea; tahini; lemon; garlic; olive oil; pita'],
  ['fried egg and toast,煎蛋吐司',
   '2 egg; toast; butter; tomato'],
  ['smoothie,奶昔',
   'banana; frozen berries; yogurt; oats; honey; milk'],
];

/* ── your dishes, as buttons ────────────────────────────────
   The default set is the five you cook; star any other dish under Setup and
   it joins them. */
const DEFAULT_FAVOURITES = ['sesame noodles', 'tuna rice bowl', 'salmon soy bowl', 'sandwich', 'marinated eggs'];
const FAV_COLORS = ['#F0B429', '#FF6B6B', '#FF7BA0', '#3FA7DC', '#9B87E0', '#3FB27F', '#F08A3C', '#2FB5A6'];

/* ── le français ────────────────────────────────────────────
   Every food again, in French, keyed by its English name. Shown beside the
   Chinese on the list and searchable like any other name — write "poulet"
   and the chicken lands in the basket. Articles are part of the entry
   because the gender is the half worth learning. */
const FR = {
  /* fruit */
  'apple': 'la pomme', 'banana': 'la banane', 'orange': "l'orange", 'mandarin': 'la mandarine',
  'grapefruit': 'le pamplemousse', 'lemon': 'le citron', 'lime': 'le citron vert', 'grape': 'le raisin',
  'strawberry': 'la fraise', 'blueberry': 'la myrtille', 'raspberry': 'la framboise', 'blackberry': 'la mûre',
  'watermelon': 'la pastèque', 'melon': 'le melon', 'pineapple': "l'ananas", 'mango': 'la mangue',
  'peach': 'la pêche', 'pear': 'la poire', 'plum': 'la prune', 'cherry': 'la cerise',
  'kiwi': 'le kiwi', 'pomegranate': 'la grenade', 'persimmon': 'le kaki', 'lychee': 'le litchi',
  'longan': 'le longane', 'dragon fruit': 'le fruit du dragon', 'papaya': 'la papaye', 'guava': 'la goyave',
  'apricot': "l'abricot", 'fig': 'la figue', 'coconut': 'la noix de coco', 'avocado': "l'avocat",
  'red date': 'la jujube', 'raisin': 'le raisin sec', 'dried cranberry': 'la canneberge séchée',

  /* légumes */
  'tomato': 'la tomate', 'cherry tomato': 'la tomate cerise', 'cucumber': 'le concombre',
  'carrot': 'la carotte', 'potato': 'la pomme de terre', 'sweet potato': 'la patate douce',
  'onion': "l'oignon", 'bell pepper': 'le poivron', 'green pepper': 'le poivron vert',
  'chili pepper': 'le piment', 'broccoli': 'le brocoli', 'cauliflower': 'le chou-fleur',
  'cabbage': 'le chou', 'napa cabbage': 'le chou chinois', 'bok choy': 'le pak choï',
  'baby bok choy': 'le petit pak choï', 'choy sum': 'le choy sum', 'chinese broccoli': 'le chou kale chinois',
  'spinach': 'les épinards', 'lettuce': 'la laitue', 'romaine': 'la romaine', 'kale': 'le chou frisé',
  'arugula': 'la roquette', 'celery': 'le céleri', 'asparagus': "l'asperge", 'zucchini': 'la courgette',
  'eggplant': "l'aubergine", 'pumpkin': 'la citrouille', 'winter melon': "la courge d'hiver",
  'bitter melon': 'le melon amer', 'luffa': 'la courge éponge', 'chayote': 'la chayote',
  'green bean': 'le haricot vert', 'snow pea': 'le pois mange-tout', 'sugar snap pea': 'le pois croquant',
  'pea': 'le petit pois', 'corn': 'le maïs', 'mushroom': 'le champignon', 'shiitake': 'le shiitaké',
  'enoki': "l'énoki", 'king oyster mushroom': 'le pleurote du panicaut', 'oyster mushroom': 'le pleurote',
  'wood ear': "l'oreille de Judas", 'bean sprout': 'le germe de soja', 'pea shoot': 'la pousse de pois',
  'lotus root': 'la racine de lotus', 'bamboo shoot': 'la pousse de bambou', 'water chestnut': "la châtaigne d'eau",
  'taro': 'le taro', 'chinese yam': "l'igname chinoise", 'daikon': 'le radis blanc', 'beetroot': 'la betterave',
  'okra': 'le gombo', 'brussels sprout': 'le chou de Bruxelles', 'celtuce': 'la laitue asperge',
  'amaranth greens': "l'amarante", 'garlic sprout': "la tige d'ail", 'chinese chives': 'la ciboule de Chine',
  'watercress': 'le cresson', 'seaweed': "l'algue", 'kelp': 'le varech',
  'pickled mustard greens': 'la moutarde marinée', 'pickle': 'le cornichon',
  'preserved vegetable': 'le légume mariné', 'olive': "l'olive",

  /* aromates */
  'garlic': "l'ail", 'ginger': 'le gingembre', 'scallion': "l'oignon vert", 'shallot': "l'échalote",
  'leek': 'le poireau', 'cilantro': 'la coriandre', 'parsley': 'le persil', 'basil': 'le basilic',
  'mint': 'la menthe', 'rosemary': 'le romarin', 'thyme': 'le thym', 'dill': "l'aneth",
  'lemongrass': 'la citronnelle',

  /* viande */
  'chicken': 'le poulet', 'chicken breast': 'le blanc de poulet', 'chicken thigh': 'la cuisse de poulet',
  'chicken wing': "l'aile de poulet", 'whole chicken': 'le poulet entier', 'chicken feet': 'la patte de poulet',
  'pork': 'le porc', 'pork belly': 'la poitrine de porc', 'pork loin': 'le filet de porc',
  'ground pork': 'le porc haché', 'pork ribs': 'les côtes de porc', 'pork shoulder': "l'épaule de porc",
  'beef': 'le bœuf', 'ground beef': 'le bœuf haché', 'steak': 'le steak', 'beef brisket': 'la poitrine de bœuf',
  'beef shank': 'le jarret de bœuf', 'lamb': "l'agneau", 'lamb chop': "la côtelette d'agneau",
  'duck': 'le canard', 'bacon': 'le bacon', 'sausage': 'la saucisse', 'ham': 'le jambon',
  'deli turkey': 'la dinde tranchée', 'prosciutto': 'le jambon cru', 'salami': 'le salami',
  'pork liver': 'le foie de porc', 'tripe': 'les tripes', 'meatball': 'la boulette de viande',

  /* poisson */
  'fish': 'le poisson', 'salmon': 'le saumon', 'tuna': 'le thon', 'cod': 'la morue',
  'sea bass': 'le bar', 'tilapia': 'le tilapia', 'grass carp': "la carpe herbivore",
  'crucian carp': 'le carassin', 'shrimp': 'la crevette', 'crab': 'le crabe', 'squid': 'le calmar',
  'clam': 'la palourde', 'mussel': 'la moule', 'scallop': 'la coquille Saint-Jacques',
  'oyster': "l'huître", 'dried shrimp': 'la crevette séchée', 'fish ball': 'la boulette de poisson',
  'eel': "l'anguille",

  /* œufs et laitages */
  'egg': "l'œuf", 'quail egg': 'le œuf de caille', 'century egg': 'le œuf de cent ans',
  'salted duck egg': 'le œuf de cane salé', 'milk': 'le lait', 'yogurt': 'le yaourt',
  'greek yogurt': 'le yaourt grec', 'cheese': 'le fromage', 'cheddar': 'le cheddar',
  'mozzarella': 'la mozzarella', 'parmesan': 'le parmesan', 'cream cheese': 'le fromage à la crème',
  'cream': 'la crème', 'sour cream': 'la crème sure', 'butter': 'le beurre',
  'condensed milk': 'le lait concentré', 'oat milk': "le lait d'avoine", 'almond milk': "le lait d'amande",

  /* soja */
  'tofu': 'le tofu', 'firm tofu': 'le tofu ferme', 'silken tofu': 'le tofu soyeux',
  'fried tofu puff': 'le tofu frit', 'dried tofu': 'le tofu séché', 'tofu skin': 'la peau de tofu',
  'tempeh': 'le tempeh', 'edamame': "l'édamame", 'soy milk': 'le lait de soja',

  /* céréales */
  'rice': 'le riz', 'jasmine rice': 'le riz jasmin', 'brown rice': 'le riz brun',
  'glutinous rice': 'le riz gluant', 'quinoa': 'le quinoa', 'oats': "les flocons d'avoine",
  'millet': 'le millet', 'barley': "l'orge", 'flour': 'la farine', 'noodles': 'les nouilles',
  'ramen': 'le ramen', 'udon': "l'udon", 'rice noodles': 'les nouilles de riz',
  'glass noodles': 'les vermicelles', 'pasta': 'les pâtes', 'penne': 'les penne',
  'lasagna sheets': 'les feuilles de lasagne', 'couscous': 'le couscous',
  'dumpling wrappers': 'les pâtes à raviolis', 'wonton wrappers': 'les pâtes à wonton',
  'spring roll wrappers': 'les galettes de riz', 'tortilla': 'la tortilla',
  'cereal': 'les céréales', 'breadcrumbs': 'la chapelure',

  /* boulangerie */
  'bread': 'le pain', 'whole wheat bread': 'le pain complet', 'toast': 'le pain de mie',
  'steamed bun': 'le pain vapeur', 'bagel': 'le bagel', 'croissant': 'le croissant',
  'pita': 'le pain pita', 'focaccia': 'la focaccia', 'cake': 'le gâteau',
  'scallion pancake': "la crêpe à l'oignon vert",

  /* légumineuses et noix */
  'black bean': 'le haricot noir', 'kidney bean': 'le haricot rouge', 'chickpea': 'le pois chiche',
  'lentil': 'la lentille', 'mung bean': 'le haricot mungo', 'red bean': 'le haricot azuki',
  'soybean': 'le soja', 'peanut': "l'arachide", 'almond': "l'amande", 'walnut': 'la noix',
  'cashew': 'la noix de cajou', 'pistachio': 'la pistache', 'pine nut': 'le pignon de pin',
  'sesame seed': 'le sésame', 'sunflower seed': 'la graine de tournesol',
  'pumpkin seed': 'la graine de courge', 'chia seed': 'la graine de chia',
  'flaxseed': 'la graine de lin', 'peanut butter': "le beurre d'arachide",

  /* épicerie */
  'soy sauce': 'la sauce soja', 'dark soy sauce': 'la sauce soja noire', 'oyster sauce': "la sauce d'huître",
  'vinegar': 'le vinaigre', 'black vinegar': 'le vinaigre noir', 'cooking wine': 'le vin de cuisine',
  'sesame oil': 'le huile de sésame', 'cooking oil': "l'huile", 'olive oil': "l'huile d'olive",
  'salt': 'le sel', 'sugar': 'le sucre', 'rock sugar': 'le sucre candi', 'brown sugar': 'la cassonade',
  'honey': 'le miel', 'chicken bouillon': 'le bouillon de poulet', 'doubanjiang': 'la pâte de fèves pimentée',
  'sweet bean sauce': 'la sauce de soja sucrée', 'hoisin sauce': 'la sauce hoisin',
  'chili oil': 'le huile pimentée', 'chili sauce': 'la sauce piquante', 'ketchup': 'le ketchup',
  'mayonnaise': 'la mayonnaise', 'mustard': 'la moutarde', 'fish sauce': 'la sauce de poisson',
  'mirin': 'le mirin', 'furikake': 'le furikake', 'curry paste': 'la pâte de curry',
  'tomato paste': 'le concentré de tomate', 'canned tomatoes': 'les tomates en conserve',
  'coconut milk': 'le lait de coco', 'stock': 'le bouillon', 'sesame paste': 'la pâte de sésame',
  'fermented black beans': 'les haricots noirs fermentés', 'fermented tofu': 'le tofu fermenté',
  'pickled chili': 'le piment mariné', 'cornstarch': 'la fécule de maïs',
  'potato starch': 'la fécule de pomme de terre', 'baking powder': 'la levure chimique',
  'yeast': 'la levure', 'vanilla extract': "l'extrait de vanille", 'jam': 'la confiture',
  'maple syrup': "le sirop d'érable",

  /* épices */
  'black pepper': 'le poivre noir', 'white pepper': 'le poivre blanc',
  'sichuan peppercorn': 'le poivre du Sichuan', 'star anise': "l'anis étoilé", 'cinnamon': 'la cannelle',
  'clove': 'le clou de girofle', 'fennel seed': 'la graine de fenouil', 'cumin': 'le cumin',
  'chili flakes': 'le piment en flocons', 'five spice powder': 'le cinq-épices',
  'thirteen spice': 'le treize-épices', 'bay leaf': 'la feuille de laurier', 'dried chili': 'le piment séché',
  'turmeric': 'le curcuma', 'paprika': 'le paprika', 'oregano': "l'origan", 'curry powder': 'le curry en poudre',
  'dried shiitake': 'le shiitaké séché', 'goji berry': 'la baie de goji',

  /* surgelés */
  'frozen dumplings': 'les raviolis surgelés', 'frozen peas': 'les petits pois surgelés',
  'frozen berries': 'les fruits rouges surgelés', 'ice cream': 'la crème glacée',

  /* boissons */
  'water': "l'eau", 'sparkling water': "l'eau pétillante", 'tea': 'le thé', 'green tea': 'le thé vert',
  'coffee': 'le café', 'orange juice': "le jus d'orange", 'juice': 'le jus', 'beer': 'la bière',
  'wine': 'le vin', 'cola': 'le cola', 'milk tea': 'le thé au lait',

  /* maison */
  'paper towels': 'le papier essuie-tout', 'toilet paper': 'le papier toilette',
  'dish soap': 'le liquide vaisselle', 'laundry detergent': 'la lessive', 'trash bags': 'les sacs poubelle',
  'aluminium foil': "le papier d'aluminium", 'plastic wrap': 'le film alimentaire',
  'sponge': "l'éponge", 'ziplock bags': 'les sacs à fermeture',
};
